### ISSUE TITLE
Disable/Ignore inactive or non-functioning Fancy_vends

### ISSUE THREAD

**Issue by thomasrudin** [minetest-mapserver/mapserver#74] opened 2019-12-25 20:49 UTC
Non-functioning:
* Full (no place for money, TODO: partial stacks)
* Empty (old behavior: empty on search-list, **new**: not on search-list)
* Unconfigured (should work right now)

**Comment by BuckarooBanzay** [comment] 2022-01-30 20:25
duplicate of #83

**Closed by BuckarooBanzay** 2022-01-30 20:25 UTC
Labels: enhancement
